"""add type to room

Revision ID: 09a84f1d20a3
Revises: 3229b20d6482
Create Date: 2026-04-22 15:26:56.007441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a84f1d20a3'
down_revision: Union[str, Sequence[str], None] = '3229b20d6482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('type', sa.String(length=255), server_default=sa.text("'dice'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'type')
    # ### end Alembic commands ###
