"""remove email field

Revision ID: 1c8db1de4429
Revises: cc0aa48f982c
Create Date: 2026-04-22 13:49:05.707193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8db1de4429'
down_revision: Union[str, Sequence[str], None] = 'cc0aa48f982c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'prize_percentage',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('rooms', 'prize_percentage',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
