"""change data type

Revision ID: 3229b20d6482
Revises: 1c8db1de4429
Create Date: 2026-04-22 14:01:23.429998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3229b20d6482'
down_revision: Union[str, Sequence[str], None] = '1c8db1de4429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'prize_percentage',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.DECIMAL(precision=4, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'prize_percentage',
               existing_type=sa.DECIMAL(precision=4, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
