"""create room table

Revision ID: 71b017d3bc49
Revises: cc72ffe7b8ee
Create Date: 2026-04-22 11:22:37.375476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b017d3bc49'
down_revision: Union[str, Sequence[str], None] = 'cc72ffe7b8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enter_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('boosted', sa.Boolean(), server_default=sa.text('False'), nullable=False),
    sa.Column('boost_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('prize_percentage', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
