"""update balance datatype

Revision ID: 8d22f9ad91a0
Revises: 3e0949f581bf
Create Date: 2026-04-22 00:51:27.460166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d22f9ad91a0'
down_revision: Union[str, Sequence[str], None] = '3e0949f581bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_account', 'balance',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.DECIMAL(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_account', 'balance',
               existing_type=sa.DECIMAL(precision=18, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
