"""add room status field

Revision ID: 991f6c7d1b12
Revises: 09a84f1d20a3
Create Date: 2026-04-22 23:08:21.607425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991f6c7d1b12'
down_revision: Union[str, Sequence[str], None] = '09a84f1d20a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_participants', sa.Column('bot_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('room_participants_boot_id_fkey'), 'room_participants', type_='foreignkey')
    op.create_foreign_key(None, 'room_participants', 'bots', ['bot_id'], ['id'])
    op.drop_column('room_participants', 'boot_id')
    op.add_column('rooms', sa.Column('room_status', sa.String(length=25), server_default=sa.text("'idle'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'room_status')
    op.add_column('room_participants', sa.Column('boot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'room_participants', type_='foreignkey')
    op.create_foreign_key(op.f('room_participants_boot_id_fkey'), 'room_participants', 'bots', ['boot_id'], ['id'])
    op.drop_column('room_participants', 'bot_id')
    # ### end Alembic commands ###
