"""create bunch of tables

Revision ID: cc0aa48f982c
Revises: 71b017d3bc49
Create Date: 2026-04-22 12:19:46.238338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0aa48f982c'
down_revision: Union[str, Sequence[str], None] = '71b017d3bc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('boot_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_boosted', sa.Boolean(), nullable=False),
    sa.Column('reserved_balance', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_wins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('bot_id', sa.UUID(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('bot_count', sa.Integer(), nullable=False),
    sa.Column('boosts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_balance_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_win_id', sa.UUID(), nullable=False),
    sa.Column('withdraw_history_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_win_id'], ['room_wins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['withdraw_history_id'], ['bank_account_withdraw_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uix_name_creator_room', 'rooms', ['creator_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_creator_room', 'rooms', type_='unique')
    op.drop_table('user_balance_changes')
    op.drop_table('room_wins')
    op.drop_table('room_participants')
    op.drop_table('bots')
    # ### end Alembic commands ###
